version = 2

[global]
dll = "/mnt/windows/Games/Steam/steamapps/common/Lossless Scaling/Lossless.dll"
allow_fp16 = true

[[profile]]
name = "vkcube-external"
active_in = "vkcube"
gpu = "AMD Radeon RX 9060 XT (RADV GFX1200)"
presentation = "external"
multiplier = 2

[[profile]]
name = "test-app"
gpu = "AMD Radeon RX 9070 XT (RADV GFX1201)"
presentation = "external"
multiplier = 2
